# Generated by Django 2.2.6 on 2019-11-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20191110_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='imagen',
            field=models.ImageField(null=True, upload_to='hoteles'),
        ),
    ]
