# Generated by Django 2.2.6 on 2019-11-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_hotel_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
