# Generated by Django 2.2.6 on 2019-11-17 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_auto_20191115_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='imagen',
        ),
    ]
