# Generated by Django 2.2.6 on 2019-11-28 21:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_remove_hotel_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
